version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - node -v
      - yarn install
  build:
    commands:
      - |
        aws amplify start-job \
          --app-id d2f1nrbpx0jyl \
          --branch-name main \
          --job-type RELEASE
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  base-directory: ./dist
  files:
    - '**/*'
