version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - node -v
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  baseDirectory: ./dist
  files:
    - '**/*'
